### ISSUE TITLE
Loop issue

### ISSUE THREAD

**Issue by philsinatra** [gnt36/idm231-gnt36#3]
The following line is invalid:

https://github.com/gnt36/idm231-gnt36/blob/c3044330cf805984cd670b673520fd0766deffb2/js/main.js#L106

Since you're using `querySelectorAll`, you should get back a node list (similar to an array) of elements. You can not apply one event listener to the entire node list; you have to apply the event listener to each item in the list. 

Start by logging the value of `gods` before running the loop:

```diff
+ console.log(gods);

for (let i = 0; i < 12; i++) {
  gods.addEventListener('click', showDiv, false);
}
```

Once you confirm you have a node list of elements, log each item from the list in your loop:

```diff
for (let i = 0; i < 12; i++) {
- gods.addEventListener('click', showDiv, false);
+ console.log(gods[i]);
}
```

Then, instead of applying the event listener to the entire node list (`gods`), apply it to each item in the list (`gods[i]`).

```diff
for (let i = 0; i < 12; i++) {
+ gods[i].addEventListener('click', showDiv, false);
}
```

**Note**: consider adjusting your original query to target the `button` elements rather than the `div` elements.

https://github.com/gnt36/idm231-gnt36/blob/c3044330cf805984cd670b673520fd0766deffb2/index.html#L35-L40

Then ask - do you need the `div` elements at all?

**Comment by gnt36** [comment]
So I updated my code from your recommendations but the only way I could figure out how to use the 'x' to toggle it closed was using an if-statement - but then the cycle only happens once, like I can't re-click the img/buttons to see the newDiv again

**Comment by philsinatra** [comment]
One function toggles the `hidden` attribute:

https://github.com/gnt36/idm231-gnt36/blob/df17172b33974ecbe38a08947f523e882557a467/js/main.js#L100-L102

while the other changes the `display` property:

https://github.com/gnt36/idm231-gnt36/blob/df17172b33974ecbe38a08947f523e882557a467/js/main.js#L108-L112

You should use the `hidden` attribute toggle to show and hide the model. To apply the event listeners, you can use a single function and a shared class.

Here's an example to guide you: https://codepen.io/philsinatra/pen/GRLrGJm

Use this as a guide; don't try to copy-paste this code directly into your project.
